repository:
  name: improving-dx-with-github
  # description: Code samples for https://medly.tech/events/improving-developer-experience-with-github
  default_branch : main
  private : true
  has_issues: false
  has_wiki: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: false
  delete_branch_on_merge: true
  topics: tech-talk, dx, github
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - is-even
      enforce_admins: null
      required_linear_history: null
      restrictions: null
