import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>web-app</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={styles.main}>
				<a href="https://github.com/niraj8/improving-dx-with-github">
					<p>Hello, Discord!</p>
					<p>./examples/web-app</p>
				</a>

				<div className={styles.grid}>
					<a href="https://github.com/niraj8/improving-dx-with-github/tree/main/examples" className={styles.card}>
						<h2>Other Examples &rarr;</h2>
					</a>

				</div>
			</main>
		</div>
	)
}
