name: ci:is-even

on:
  pull_request: {}
  push:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./examples/is-even

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '14'
      - run: npm ci
      - run: npm test
